### ISSUE TITLE
User having issue with FU SAIL

### ISSUE THREAD

**Issue by Fevix** [xn-5o8h/FUSAILModdedRaceSupport#1] opened 2018-08-08 15:56 UTC
Avali-Triage-Team/Avali#396

User was instructed to install your mod, and seems to have done so properly. Is there some change I need to do?

**Comment by xn-5o8h** [comment] 2018-08-22 06:42
woahwoops apparently I don't get mail notifications from this, sorry for the delay!

This doesn't seem to be a problem with this mod tho, as the UI is loading and it's all this mod does, patching the techstations; I believe it's an issue to be posted to https://github.com/zimberzimber/Ztarbound , with a log

Edit: I'm unable to reproduce the issue with Avali (Triage) and ztarbound from the workshop; maybe that user was using an older version of FU or this mod, as the scripts' location changed since then?

**Comment by xn-5o8h** [comment] 2018-08-24 12:51
Closing that issue here as the source ended up being a modded pet script crashing, bringing down the whole techstation's script https://github.com/Avali-Triage-Team/Avali/issues/396#issuecomment-415587554

**Closed as completed by xn-5o8h** 2018-08-24 12:51 UTC
